import { CalendarRange, Download, Filter, PackageCheck, Truck } from "lucide-react";
import Link from "next/link";
import { EmptyState } from "@/components/feedback/empty-state";
import { MotionPage } from "@/components/motion/motion-page";
import { MotionSection } from "@/components/motion/motion-section";
import { formatStatusLabel } from "@/lib/status-labels";
import { reportSearchParams } from "../filters";
import type { GuideReportData, GuideReportFilters, ReportOption } from "../types";

function Select({ name, label, value, options, children }: { name: string; label: string; value?: string; options?: ReportOption[]; children?: React.ReactNode }) { return <label className="min-w-0 text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">{label}</span><select name={name} defaultValue={value ?? ""} className="min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground"><option value="">Todos</option>{children ?? options?.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
function quantity(value: number) { return new Intl.NumberFormat("es-GT", { maximumFractionDigits: 3 }).format(value); }
function dateTime(value: string, timezone: string) { return new Intl.DateTimeFormat("es-GT", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(value)); }

export function GuideReport({ data, filters }: { data: GuideReportData; filters: GuideReportFilters }) {
  const dispatchCount = data.programming.reduce((sum, item) => sum + item.dispatches.length, 0); const reconciled = data.rows.filter((row) => row.reconciliationStatus === "MATCHED").length; const reinvoicing = data.rows.filter((row) => row.reinvoicingRequired).length;
  return <MotionPage className="mx-auto max-w-[1600px]">
    <MotionSection className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-strong">Control operacional</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">Reporte de Programaciones</h1><p className="mt-2 text-sm text-foreground-muted">Cada Programación agrupa sus Despachos, Guías, Pedidos, Facturas y resultado de conciliación.</p></div><Link href={`/reports/export?${reportSearchParams(filters)}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-brand px-4 text-sm font-semibold text-white"><Download className="size-4" />Exportar Excel</Link></MotionSection>

    <MotionSection className="mt-5 rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="flex items-center gap-2"><Filter className="size-4 text-brand-strong" /><h2 className="font-semibold text-foreground">Filtros de Programaciones y Despachos</h2></div><form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
      <label className="text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">Período</span><select name="period" defaultValue={filters.period ?? "month"} className="min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground"><option value="day">Hoy</option><option value="week">Esta semana</option><option value="month">Este mes</option><option value="custom">Rango personalizado</option></select></label>
      <label className="text-xs text-foreground-muted"><span className="mb-1.5 block">Desde</span><input type="date" name="from" defaultValue={filters.dateFrom} className="min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground" /></label><label className="text-xs text-foreground-muted"><span className="mb-1.5 block">Hasta</span><input type="date" name="to" defaultValue={filters.dateTo} className="min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground" /></label>
      <Select name="project" label="Proyecto" value={filters.projectId} options={data.filters.projects} /><Select name="supplier" label="Proveedor" value={filters.supplierId} options={data.filters.suppliers} /><Select name="programmingStatus" label="Estado de Programación" value={filters.programmingStatus}><option value="DRAFT">Borrador</option><option value="PENDING_CONFIRMATION">Pendiente de confirmación</option><option value="CONFIRMED">Confirmada</option><option value="IN_EXECUTION">En ejecución</option><option value="COMPLETED">Completada</option><option value="CANCELLED">Cancelada</option></Select>
      <Select name="user" label="Creado o registrado por" value={filters.userId} options={data.filters.users} /><label className="text-xs text-foreground-muted"><span className="mb-1.5 block">Pedido</span><input name="order" defaultValue={filters.orderNumber ?? ""} placeholder="Ej. 47" className="min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground" /></label><Select name="batch" label="Lote" value={filters.batchId} options={data.filters.batches} />
      <Select name="dispatchStatus" label="Estado del Despacho" value={filters.dispatchStatus}><option value="REGISTERED">Registrado</option><option value="BATCHED">En lote</option><option value="RECONCILED">Conciliado</option><option value="REQUIRES_CORRECTION">Requiere corrección</option></Select><Select name="orderStatus" label="Estado del Pedido" value={filters.orderStatus}><option value="COMPLETED">Completado</option><option value="PENDING">Pendiente</option><option value="REINVOICING">Con refacturación requerida</option></Select><Select name="reconciliation" label="Conciliación" value={filters.reconciliationStatus}><option value="MATCHED">Conciliado</option><option value="WITH_DIFFERENCES">Con diferencias</option><option value="PARTIAL">Parcial</option><option value="NO_INVOICES">Sin factura</option><option value="REQUIRES_REVIEW">Requiere revisión</option><option value="WITHOUT_ORDER">Sin Pedido</option></Select><Select name="incidents" label="Incidencias" value={filters.withIncidents}><option value="yes">Con incidencias</option><option value="no">Sin incidencias</option></Select>
      <div className="flex items-end gap-2"><button className="min-h-11 flex-1 rounded-lg bg-foreground px-4 text-sm font-semibold text-surface">Aplicar</button><Link href="/reports" className="inline-flex min-h-11 items-center rounded-lg border border-border px-3 text-sm text-foreground-muted">Limpiar</Link></div>
    </form></MotionSection>

    <MotionSection className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><article className="rounded-xl border border-border bg-surface p-4"><CalendarRange className="size-4 text-brand-strong" /><p className="mt-3 text-2xl font-semibold text-foreground">{data.programming.length}</p><p className="mt-1 text-xs text-foreground-muted">Programaciones</p></article><article className="rounded-xl border border-border bg-surface p-4"><Truck className="size-4 text-brand-strong" /><p className="mt-3 text-2xl font-semibold text-foreground">{dispatchCount}</p><p className="mt-1 text-xs text-foreground-muted">Despachos relacionados</p></article><article className="rounded-xl border border-border bg-surface p-4"><PackageCheck className="size-4 text-success" /><p className="mt-3 text-2xl font-semibold text-foreground">{reconciled}</p><p className="mt-1 text-xs text-foreground-muted">Despachos conciliados</p></article><article className="rounded-xl border border-border bg-surface p-4"><PackageCheck className="size-4 text-destructive" /><p className="mt-3 text-2xl font-semibold text-foreground">{reinvoicing}</p><p className="mt-1 text-xs text-foreground-muted">Requirieron refacturación</p></article></MotionSection>

    <MotionSection className="mt-4 space-y-3">{!data.programming.length ? <div className="rounded-xl border border-border bg-surface p-6"><EmptyState title="Sin Programaciones" description="No hay Programaciones que coincidan con el período y los filtros seleccionados." /></div> : data.programming.map((program) => <article key={program.id} className="overflow-hidden rounded-xl border border-border bg-surface"><header className="grid gap-4 border-b border-border p-4 sm:p-5 lg:grid-cols-[1.4fr_repeat(4,1fr)_auto] lg:items-center"><div><Link href={`/programming/${program.id}`} className="font-mono text-base font-semibold text-brand-strong hover:underline">{program.code}</Link><p className="mt-1 text-xs text-foreground-muted">{program.projectName} · {program.supplierName}</p></div><div className="text-xs"><p className="text-foreground-muted">Fecha programada</p><p className="mt-1 font-semibold text-foreground">{dateTime(program.scheduledAt, program.timezone)}</p></div><div className="text-xs"><p className="text-foreground-muted">Cantidad</p><p className="mt-1 font-semibold text-foreground">{quantity(program.confirmedQuantity ?? program.requestedQuantity)} {program.unitCode}</p></div><div className="text-xs"><p className="text-foreground-muted">Estado</p><p className="mt-1 font-semibold text-foreground">{formatStatusLabel(program.status)}</p></div><div className="text-xs"><p className="text-foreground-muted">Despachos</p><p className="mt-1 font-semibold text-foreground">{program.dispatches.length}</p></div><Link href={`/programming/${program.id}`} className="inline-flex min-h-10 items-center justify-center rounded-lg border border-border px-3 text-xs font-semibold text-foreground">Ver Programación</Link></header>
        {!program.dispatches.length ? <div className="p-5 text-sm text-foreground-muted">Esta Programación todavía no tiene Despachos relacionados.</div> : <div className="divide-y divide-border">{program.dispatches.map((dispatch) => <div key={dispatch.dispatchId} className="grid gap-4 p-4 sm:p-5 lg:grid-cols-[1.2fr_repeat(5,1fr)_auto] lg:items-center"><div><Link href={`/dispatches/${dispatch.dispatchId}`} className="font-semibold text-brand-strong hover:underline">{dispatch.guideNumber}</Link><p className="mt-1 text-xs text-foreground-muted">Despacho #{dispatch.dispatchId.slice(0, 8).toUpperCase()}</p></div><div className="text-xs"><p className="text-foreground-muted">Despachado / recibido</p><p className="mt-1 font-semibold text-foreground">{quantity(dispatch.documentedQuantity)} / {quantity(dispatch.receivedQuantity)} {dispatch.unitCode}</p></div><div className="text-xs"><p className="text-foreground-muted">Pedido / lote</p><p className="mt-1 font-semibold text-foreground">{dispatch.orderNumber ?? "Sin Pedido"}</p><p className="text-foreground-muted">{dispatch.batchCode ?? "Sin lote"}</p></div><div className="text-xs"><p className="text-foreground-muted">Despacho</p><p className="mt-1 font-semibold text-foreground">{formatStatusLabel(dispatch.dispatchStatus)}</p></div><div className="text-xs"><p className="text-foreground-muted">Conciliación</p><p className="mt-1 font-semibold text-foreground">{formatStatusLabel(dispatch.reconciliationStatus)}</p></div><div className="text-xs"><p className="text-foreground-muted">Refacturación</p><p className={`mt-1 font-semibold ${dispatch.reinvoicingRequired ? "text-destructive" : "text-success"}`}>{dispatch.reinvoicingRequired ? "Sí requirió" : dispatch.reconciliationStatus === "MATCHED" ? "No requirió" : "Pendiente"}</p></div><Link href={`/dispatches/${dispatch.dispatchId}`} className="inline-flex min-h-10 items-center justify-center rounded-lg bg-foreground px-3 text-xs font-semibold text-surface">Ver Despacho</Link></div>)}</div>}
      </article>)}</MotionSection>
  </MotionPage>;
}
