import { AlertTriangle, CalendarRange, CheckCircle2, FileText, Filter, Package, RotateCcw, Truck } from "lucide-react";
import Link from "next/link";

import { EmptyState } from "@/components/feedback/empty-state";
import { MotionPage } from "@/components/motion/motion-page";
import { MotionSection } from "@/components/motion/motion-section";
import { StatusBadge, type BadgeTone } from "@/components/ui/badge";
import { formatStatusLabel } from "@/lib/status-labels";

import { reportSearchParams } from "../filters";
import type { GuideReportData, GuideReportFilters, GuideReportRow, ReportInvoice, ReportOption } from "../types";
import { ReportExportActions } from "./report-export-actions";

function Select({ name, label, value, options, children }: { name: string; label: string; value?: string; options?: ReportOption[]; children?: React.ReactNode }) {
  return <label className="min-w-0 text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">{label}</span><select name={name} defaultValue={value ?? ""} className="form-input"><option value="">Todos</option>{children ?? options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
}

function quantity(value: number) { return new Intl.NumberFormat("es-GT", { maximumFractionDigits: 3 }).format(value); }
function money(value: number, currency: string) { return new Intl.NumberFormat("es-GT", { style: "currency", currency, minimumFractionDigits: 2 }).format(value); }
function dateTime(value: string, timezone: string) { return new Intl.DateTimeFormat("es-GT", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(value)); }

function statusTone(status: string): BadgeTone {
  if (["RECONCILED", "COMPLETED", "CONFIRMED", "REGISTERED"].includes(status)) return "success";
  if (["WITH_DIFFERENCES", "PENDING_REINVOICING"].includes(status)) return "warning";
  if (["CANCELLED", "NON_PROCEEDING"].includes(status)) return "danger";
  if (["IN_EXECUTION", "PENDING_RECONCILIATION"].includes(status)) return "info";
  return "neutral";
}

function InvoiceLine({ label, invoice }: { label: string; invoice: ReportInvoice | null }) {
  return <div className="grid min-w-0 gap-2 rounded-lg border border-border/80 bg-background/55 px-3 py-2.5 min-[390px]:grid-cols-[minmax(0,1fr)_auto] min-[390px]:items-center"><div className="flex min-w-0 items-center gap-2.5"><span className={`grid size-7 shrink-0 place-items-center rounded-md ${invoice ? "bg-success-soft text-success" : "bg-muted text-foreground-muted"}`}><FileText className="size-3.5" /></span><div className="min-w-0"><p className="text-[11px] font-medium text-foreground-muted">{label}</p><p className="truncate text-sm font-semibold text-foreground">{invoice?.number ?? "Pendiente"}</p></div></div>{invoice && <div className="pl-9 text-left min-[390px]:pl-0 min-[390px]:text-right"><p className="text-xs font-semibold text-foreground">{money(invoice.total, invoice.currency)}</p><p className="text-[10px] text-foreground-muted">{formatStatusLabel(invoice.extractionStatus, "Sin extracción")}</p></div>}</div>;
}

function DispatchBlock({ dispatch }: { dispatch: GuideReportRow }) {
  return <section className="rounded-xl border border-border bg-background/40 p-4 sm:p-5"><div className="flex flex-col gap-4 xl:grid xl:grid-cols-[minmax(0,1.2fr)_minmax(240px,.8fr)_minmax(300px,1fr)_auto] xl:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/dispatches/${dispatch.dispatchId}`} className="font-mono text-sm font-semibold text-brand-strong hover:underline">{dispatch.dispatchCode}</Link><StatusBadge label={formatStatusLabel(dispatch.dispatchStatus)} tone={statusTone(dispatch.dispatchStatus)} /></div><div className="mt-3 grid grid-cols-2 gap-x-5 gap-y-3 text-xs sm:grid-cols-3"><div><p className="text-foreground-muted">Pedido</p><p className="mt-0.5 font-semibold text-foreground">{dispatch.orderNumber ?? "Sin pedido"}</p></div><div><p className="text-foreground-muted">Lote</p><p className="mt-0.5 font-semibold text-foreground">{dispatch.batchCode ?? "Sin lote"}</p></div><div><p className="text-foreground-muted">Volumen real</p><p className="mt-0.5 font-semibold text-foreground">{quantity(dispatch.receivedQuantity)} {dispatch.unitCode}</p></div><div><p className="text-foreground-muted">Guías</p><p className="mt-0.5 font-semibold text-foreground">{dispatch.guideCount}</p></div><div><p className="text-foreground-muted">Incidencias</p><p className="mt-0.5 font-semibold text-foreground">{dispatch.incidentCount}</p></div></div></div><div><p className="text-[11px] font-semibold uppercase tracking-[.1em] text-foreground-muted">Conciliación</p><div className="mt-2 flex flex-wrap items-center gap-2"><StatusBadge label={formatStatusLabel(dispatch.reconciliationStatus)} tone={statusTone(dispatch.reconciliationStatus)} dot /><span className="text-xs text-foreground-muted">Diferencia: <strong className={dispatch.difference === 0 ? "text-success" : "text-destructive"}>{quantity(dispatch.difference)} {dispatch.unitCode}</strong></span></div></div><div className="grid gap-2"><InvoiceLine label="Factura de producto" invoice={dispatch.productInvoice} /><InvoiceLine label="Factura de servicio" invoice={dispatch.serviceInvoice} /></div><Link href={`/dispatches/${dispatch.dispatchId}`} className="secondary-button w-full text-xs xl:w-auto">Ver despacho</Link></div></section>;
}

function Kpi({ icon: Icon, label, value, tone = "brand" }: { icon: typeof CalendarRange; label: string; value: number; tone?: "brand" | "success" | "warning" }) {
  const iconTone = tone === "success" ? "bg-success-soft text-success" : tone === "warning" ? "bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200" : "bg-brand-soft text-brand-strong";
  return <article className="flex items-center gap-3 rounded-xl border border-border bg-surface p-4"><span className={`grid size-9 shrink-0 place-items-center rounded-lg ${iconTone}`}><Icon className="size-4" /></span><div><p className="text-xl font-semibold leading-none text-foreground">{value}</p><p className="mt-1.5 text-xs text-foreground-muted">{label}</p></div></article>;
}

export function GuideReport({ data, filters }: { data: GuideReportData; filters: GuideReportFilters }) {
  const dispatchCount = data.rows.length;
  const reconciled = data.rows.filter((row) => row.reconciliationStatus === "RECONCILED").length;
  const pendingOrDifferent = data.rows.filter((row) => row.reconciliationStatus !== "RECONCILED").length;

  return <MotionPage className="mx-auto max-w-[1500px]"><MotionSection className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-strong">Control operacional</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Reportería</h1><p className="mt-2 max-w-3xl text-sm text-foreground-muted">Trazabilidad de Programaciones, Despachos, Lotes, Facturas y Conciliación.</p></div><ReportExportActions query={reportSearchParams(filters).toString()} /></MotionSection>

    <MotionSection className="mt-5 rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="flex items-center gap-2"><Filter className="size-4 text-brand-strong" /><div><h2 className="font-semibold text-foreground">Filtros del reporte</h2><p className="mt-0.5 text-xs text-foreground-muted">Excel y ZIP utilizarán exactamente este resultado.</p></div></div><form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
      <label className="text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">Período</span><select name="period" defaultValue={filters.period ?? "month"} className="form-input"><option value="day">Hoy</option><option value="week">Esta semana</option><option value="month">Este mes</option><option value="custom">Rango personalizado</option></select></label>
      <label className="text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">Desde</span><input type="date" name="from" defaultValue={filters.dateFrom} className="form-input" /></label><label className="text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">Hasta</span><input type="date" name="to" defaultValue={filters.dateTo} className="form-input" /></label>
      <Select name="project" label="Proyecto" value={filters.projectId} options={data.filters.projects} /><Select name="supplier" label="Proveedor" value={filters.supplierId} options={data.filters.suppliers} /><Select name="programmingStatus" label="Estado de Programación" value={filters.programmingStatus}><option value="DRAFT">Borrador</option><option value="PENDING_CONFIRMATION">Pendiente de confirmación</option><option value="CONFIRMED">Confirmada</option><option value="IN_EXECUTION">En ejecución</option><option value="COMPLETED">Completada</option><option value="CANCELLED">Cancelada</option></Select>
      <Select name="user" label="Creado o registrado por" value={filters.userId} options={data.filters.users} /><label className="text-xs font-medium text-foreground-muted"><span className="mb-1.5 block">Pedido</span><input name="order" defaultValue={filters.orderNumber ?? ""} placeholder="Ej. 47" className="form-input" /></label><Select name="batch" label="Lote" value={filters.batchId} options={data.filters.batches} />
      <Select name="dispatchStatus" label="Estado del Despacho" value={filters.dispatchStatus}><option value="IN_EXECUTION">En ejecución</option><option value="COMPLETED">Completado</option></Select><Select name="orderStatus" label="Estado del Pedido" value={filters.orderStatus}><option value="COMPLETED">Completado</option><option value="PENDING">Pendiente</option><option value="REINVOICING">Con refacturación requerida</option></Select><Select name="reconciliation" label="Conciliación" value={filters.reconciliationStatus}><option value="MATCHED">Conciliado</option><option value="WITH_DIFFERENCES">Con diferencias</option><option value="PARTIAL">Parcial</option><option value="NO_INVOICES">Sin factura</option><option value="REQUIRES_REVIEW">Requiere revisión</option><option value="WITHOUT_ORDER">Sin Pedido</option></Select><Select name="incidents" label="Incidencias" value={filters.withIncidents}><option value="yes">Con incidencias</option><option value="no">Sin incidencias</option></Select>
      <div className="flex items-end gap-2 sm:col-span-2 lg:col-span-1"><button className="primary-button flex-1">Aplicar</button><Link href="/reports" className="secondary-button"><RotateCcw className="size-3.5" />Limpiar</Link></div>
    </form></MotionSection>

    <MotionSection className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi icon={CalendarRange} label="Programaciones" value={data.programming.length} /><Kpi icon={Truck} label="Despachos" value={dispatchCount} /><Kpi icon={CheckCircle2} label="Conciliados" value={reconciled} tone="success" /><Kpi icon={AlertTriangle} label="Con diferencias / pendientes" value={pendingOrDifferent} tone="warning" /></MotionSection>

    <MotionSection className="mt-4 space-y-3">{!data.programming.length ? <div className="rounded-xl border border-border bg-surface p-6"><EmptyState title="Sin Programaciones" description="No hay Programaciones que coincidan con el período y los filtros seleccionados." /></div> : data.programming.map((program) => <article key={program.id} className="overflow-hidden rounded-xl border border-border bg-surface"><header className="flex flex-col gap-4 border-b border-border px-4 py-4 sm:px-5 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/programming/${program.id}`} className="font-mono text-sm font-semibold text-brand-strong hover:underline">{program.code}</Link><StatusBadge label={formatStatusLabel(program.status)} tone={statusTone(program.status)} /></div><p className="mt-1.5 text-sm font-semibold text-foreground">{program.supplierName}</p><p className="mt-1 text-xs text-foreground-muted">{dateTime(program.scheduledAt, program.timezone)} · {quantity(program.confirmedQuantity ?? program.requestedQuantity)} {program.unitCode} · {program.projectName}</p></div><div className="flex items-center gap-3"><span className="inline-flex items-center gap-1.5 text-xs text-foreground-muted"><Package className="size-3.5" />{program.dispatches.length} despacho(s)</span><Link href={`/programming/${program.id}`} className="ghost-button text-xs">Ver programación</Link></div></header>
      {!program.dispatches.length ? <div className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div className="flex items-center gap-2 text-sm text-foreground-muted"><Truck className="size-4" /><span>Sin despacho asociado</span></div><Link href={`/programming/${program.id}`} className="secondary-button w-full text-xs sm:w-auto">Ver programación</Link></div> : <div className="space-y-3 p-3 sm:p-4">{program.dispatches.map((dispatch) => <DispatchBlock key={dispatch.dispatchId} dispatch={dispatch} />)}</div>}
    </article>)}</MotionSection>
  </MotionPage>;
}
