import { AlertTriangle, ArrowRight, CalendarCheck, CalendarDays, CheckCircle2, Clock3, FolderKanban, History, PackageCheck, ReceiptText, RefreshCcw, Scale, Truck } from "lucide-react";
import Link from "next/link";
import { MotionPage } from "@/components/motion/motion-page";
import { MotionItem, MotionList } from "@/components/motion/motion-list";
import { MotionSection } from "@/components/motion/motion-section";
import { AnimatedProgress } from "@/components/feedback/animated-progress";
import type { ProjectSummary } from "@/features/projects/types";
import { formatStatusLabel } from "@/lib/status-labels";
import { formatDashboardActivity, formatDashboardDateTime, formatDateRange, formatQuantity } from "../formatters";
import type { ProjectDashboardData } from "../types";
import { OrderStatusChart, WeeklyVolumeChart } from "./dashboard-charts";

type Focus = "GENERAL" | "PLANNING" | "RECEPTION" | "PURCHASING";
function focus(roleCodes: string[]): Focus { if (roleCodes.includes("COMPANY_ADMIN")) return "GENERAL"; if (roleCodes.includes("PURCHASING")) return "PURCHASING"; if (roleCodes.includes("RECEPTION")) return "RECEPTION"; return "PLANNING"; }
const focusLabel = { GENERAL: "Visión general", PLANNING: "Enfoque de planificación", RECEPTION: "Enfoque de recepción", PURCHASING: "Enfoque de compras" };
function Metric({ title, value, detail, icon }: { title: string; value: string; detail: string; icon: React.ReactNode }) { return <article className="rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-foreground-muted">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-foreground">{value}</p><p className="mt-1 text-xs text-foreground-muted">{detail}</p></div><div className="grid size-9 place-items-center rounded-lg bg-brand-soft text-brand-strong">{icon}</div></div></article>; }
function MiniStat({ label, value, tone = "default" }: { label: string; value: number; tone?: "default" | "danger" | "success" }) { return <div className={`rounded-lg p-3 ${tone === "danger" ? "bg-destructive-soft text-destructive" : tone === "success" ? "bg-success-soft text-success" : "bg-muted text-foreground"}`}><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-foreground-muted">{label}</p></div>; }
function Attention({ href, label, value, icon }: { href: string; label: string; value: number; icon: React.ReactNode }) { return <Link href={href} className="flex items-center gap-3 rounded-lg border border-border bg-surface p-3 transition hover:border-brand/30 hover:bg-brand-soft/20"><span className="grid size-9 place-items-center rounded-lg bg-destructive-soft text-destructive">{icon}</span><span className="min-w-0 flex-1 text-sm font-medium text-foreground">{label}</span><strong className="text-lg text-destructive">{value}</strong><ArrowRight className="size-4 text-foreground-muted" /></Link>; }
function activityHref(type: string, id: string) { if (type === "dispatch" || type === "dispatch_guide") return `/dispatches/${id}`; if (type === "programming") return `/programming/${id}`; if (type === "invoice") return "/invoices"; if (type === "reconciliation_order") return "/reconciliation"; return "/reports"; }

export function ProjectDashboard({ project, roleCodes, data }: { project: ProjectSummary; roleCodes: string[]; data: ProjectDashboardData }) {
  const mode = focus(roleCodes);
  const attention = Object.values(data.metrics.attention).some((value) => value > 0);
  return <MotionPage className="mx-auto max-w-[1500px]">
    <MotionSection className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-strong">Dashboard operacional</p><span className="rounded-full bg-muted px-2.5 py-1 text-[10px] font-semibold text-foreground-muted">{focusLabel[mode]}</span></div><h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{project.name}</h1><p className="mt-2 text-sm text-foreground-muted">{project.companyName} · Semana {formatDateRange(data.weekStart, data.weekEnd, data.timezone)}</p></div><span className="rounded-lg border border-border bg-surface px-3 py-2 text-xs text-foreground-muted"><Clock3 className="mr-2 inline size-4 text-brand-strong" />{data.timezone}</span></MotionSection>

    <MotionList className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MotionItem><Metric title="Programaciones de hoy" value={String(data.metrics.today.total)} detail={`${formatQuantity(data.metrics.today.programmedM3)} M3 · ${data.metrics.today.completed} completadas · ${data.metrics.today.pending} pendientes`} icon={<CalendarDays className="size-4" />} /></MotionItem>
      <MotionItem><Metric title="Programaciones de la semana" value={`${data.metrics.week.completed} / ${data.metrics.week.total}`} detail={`${data.metrics.week.compliance}% de cumplimiento`} icon={<CalendarCheck className="size-4" />} /></MotionItem>
      <MotionItem><Metric title="Ejecución del mes" value={`${data.metrics.month.execution}%`} detail={`${formatQuantity(data.metrics.month.receivedM3)} de ${formatQuantity(data.metrics.month.programmedM3)} M3`} icon={<Truck className="size-4" />} /></MotionItem>
      <MotionItem><Metric title="Pedidos completados" value={String(data.metrics.orders.completed)} detail={`${data.metrics.orders.pending} pendientes · ${data.metrics.orders.reinvoicing} en refacturación`} icon={<PackageCheck className="size-4" />} /></MotionItem>
    </MotionList>

    <div className="mt-4 grid gap-4 xl:grid-cols-12">
      <MotionSection className="rounded-xl border border-border bg-surface p-4 sm:p-5 xl:col-span-8"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-foreground">Cumplimiento semanal</h2><p className="mt-1 text-xs text-foreground-muted">Programaciones completadas</p></div><strong className="text-2xl text-foreground">{data.metrics.week.compliance}%</strong></div><AnimatedProgress className="mt-4" value={data.metrics.week.compliance} label="Cumplimiento semanal" /><p className="mt-2 text-xs text-foreground-muted">{data.metrics.week.completed} de {data.metrics.week.total} completadas · {data.metrics.week.pending} pendientes</p>
        <div className="mt-6 border-t border-border pt-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-display text-sm text-foreground">Programado vs recibido por día</h3><div className="flex gap-3 text-[10px] text-foreground-muted"><span><i className="mr-1 inline-block size-2 rounded-full bg-brand" />Programado</span><span><i className="mr-1 inline-block size-2 rounded-full bg-foreground-muted" />Recibido</span></div></div><WeeklyVolumeChart days={data.weekDays} /></div>
      </MotionSection>
      <MotionSection className="rounded-xl border border-border bg-surface p-4 sm:p-5 xl:col-span-4"><h2 className="font-semibold text-foreground">Estado de Pedidos</h2><p className="mt-1 text-xs text-foreground-muted">Resumen del proyecto</p><OrderStatusChart orders={data.metrics.orders} /><div className="mt-4 grid grid-cols-3 gap-2"><MiniStat label="Completados" value={data.metrics.orders.completed} tone="success" /><MiniStat label="Pendientes" value={data.metrics.orders.pending} /><MiniStat label="Refacturación" value={data.metrics.orders.reinvoicing} tone="danger" /></div><Link href="/reconciliation" className="mt-4 inline-flex w-full min-h-10 items-center justify-center gap-2 rounded-lg border border-border text-xs font-semibold text-foreground">Ver conciliación <ArrowRight className="size-3.5" /></Link></MotionSection>
    </div>

    <div className="mt-4 grid gap-4 lg:grid-cols-2">
      <MotionSection className="rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="flex items-center gap-2">{attention ? <AlertTriangle className="size-4 text-destructive" /> : <CheckCircle2 className="size-4 text-success" />}<h2 className="font-semibold text-foreground">Requieren atención</h2></div><div className="mt-4 grid gap-2">{!attention ? <p className="rounded-lg bg-success-soft p-4 text-sm font-medium text-success">Sin alertas operativas importantes.</p> : <>{data.metrics.attention.reinvoicing > 0 && <Attention href="/reconciliation?status=WITH_DIFFERENCES" label="Pedidos en refacturación" value={data.metrics.attention.reinvoicing} icon={<RefreshCcw className="size-4" />} />}{data.metrics.attention.overdueProgramming > 0 && <Attention href="/programming?status=overdue" label="Programaciones vencidas" value={data.metrics.attention.overdueProgramming} icon={<CalendarDays className="size-4" />} />}{data.metrics.attention.pendingInvoice > 0 && <Attention href="/reconciliation?status=NO_INVOICES" label="Pedidos pendientes de factura" value={data.metrics.attention.pendingInvoice} icon={<ReceiptText className="size-4" />} />}{data.metrics.attention.differences > 0 && <Attention href="/reconciliation?status=WITH_DIFFERENCES" label="Conciliaciones con diferencia" value={data.metrics.attention.differences} icon={<Scale className="size-4" />} />}</>}</div></MotionSection>
      <MotionSection className="overflow-hidden rounded-xl border border-border bg-surface"><header className="flex items-center gap-2 border-b border-border p-4 sm:p-5"><History className="size-4 text-brand-strong" /><h2 className="font-semibold text-foreground">Actividad reciente</h2></header><div className="divide-y divide-border">{data.activity.length ? data.activity.map((item) => <Link href={activityHref(item.entityType, item.entityId)} key={item.id} className="flex items-start gap-3 p-4 hover:bg-muted/40"><span className="mt-1 size-2 rounded-full bg-brand" /><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-foreground">{formatDashboardActivity(item.action)}</span><span className="mt-1 block text-xs text-foreground-muted">{item.actorName} · {formatDashboardDateTime(item.createdAt, data.timezone)}</span></span><ArrowRight className="size-4 text-foreground-muted" /></Link>) : <p className="p-6 text-center text-sm text-foreground-muted">Sin actividad reciente.</p>}</div></MotionSection>
    </div>

    {data.currentBatch && <MotionSection className="mt-4 flex flex-col gap-3 rounded-xl border border-border bg-surface p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-brand-soft text-brand-strong"><FolderKanban className="size-4" /></span><div><p className="font-semibold text-foreground">{data.currentBatch.code}</p><p className="mt-1 text-xs text-foreground-muted">Lote semanal · {data.currentBatch.activeGuideCount} guías activas · {formatStatusLabel(data.currentBatch.status)}</p></div></div><Link href={`/batches/${data.currentBatch.id}`} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-border px-3 text-xs font-semibold text-foreground">Ver lote <ArrowRight className="size-3.5" /></Link></MotionSection>}
  </MotionPage>;
}
