import { AlertTriangle, Bell, CalendarClock, Check, CheckCheck, FileClock, ReceiptText } from "lucide-react";
import Link from "next/link";
import { EmptyState } from "@/components/feedback/empty-state";
import { MotionPage } from "@/components/motion/motion-page";
import { markAllNotificationsRead, markNotificationRead } from "../actions";
import type { OperationalNotification } from "../types";

const icons = { PROGRAMMING: CalendarClock, INVOICE: ReceiptText, RECONCILIATION: AlertTriangle, INCIDENT: AlertTriangle, DOCUMENT: FileClock };
export function NotificationsCenter({ notifications, projectId, timezone }: { notifications: OperationalNotification[]; projectId: string; timezone: string }) { const unread = notifications.filter((n) => !n.read).length; return <MotionPage className="mx-auto max-w-5xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-strong">Centro operativo</p><h1 className="mt-2 text-2xl font-semibold text-foreground sm:text-3xl">Notificaciones</h1><p className="mt-2 text-sm text-foreground-muted">Solo eventos accionables del proyecto actual.</p></div>{unread > 0 && <form action={markAllNotificationsRead}><input type="hidden" name="projectId" value={projectId} /><button className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-border bg-surface px-4 text-sm font-semibold text-foreground hover:bg-muted"><CheckCheck className="size-4" />Marcar todas como leídas</button></form>}</div>
    <section className="mt-5 overflow-hidden rounded-xl border border-border bg-surface"><header className="flex items-center justify-between border-b border-border p-4 sm:p-5"><h2 className="flex items-center gap-2 font-semibold text-foreground"><Bell className="size-4 text-brand-strong" />Actividad que requiere atención</h2><span className="rounded-full bg-brand-soft px-2.5 py-1 text-xs font-semibold text-brand-strong">{unread} sin leer</span></header>{!notifications.length ? <div className="p-6"><EmptyState title="Sin notificaciones pendientes" description="No hay eventos operativos que requieran tu atención." /></div> : <div className="divide-y divide-border">{notifications.map((item) => { const Icon = icons[item.type]; return <article key={item.key} className={`grid gap-3 p-4 sm:grid-cols-[auto_1fr_auto] sm:items-center sm:p-5 ${item.read ? "opacity-65" : "bg-brand-soft/20"}`}><div className="grid size-10 place-items-center rounded-lg bg-muted text-brand-strong"><Icon className="size-4" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-foreground">{item.title}</h3>{!item.read && <span className="size-2 rounded-full bg-brand" aria-label="No leída" />}</div><p className="mt-1 text-sm text-foreground-muted">{item.description}</p><p className="mt-2 text-xs text-foreground-muted">{item.projectName} · {new Intl.DateTimeFormat("es-GT", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(item.createdAt))}</p></div><div className="flex flex-wrap gap-2 sm:justify-end"><Link href={item.href} className="inline-flex min-h-10 items-center rounded-lg bg-foreground px-3 text-xs font-semibold text-surface">Ver registro</Link>{!item.read && <form action={markNotificationRead}><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="key" value={item.key} /><button className="inline-flex min-h-10 items-center gap-1.5 rounded-lg border border-border px-3 text-xs font-semibold text-foreground"><Check className="size-3.5" />Marcar leída</button></form>}</div></article>; })}</div>}</section></MotionPage>; }
