"use client";

import { CalendarRange, ChevronRight, ClipboardCheck, FolderKanban, History, Plus, RotateCcw } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { EmptyState } from "@/components/feedback/empty-state";
import { MotionPage } from "@/components/motion/motion-page";
import { MotionSection } from "@/components/motion/motion-section";
import type { ProjectSummary } from "@/features/projects/types";

import { formatBatchDate, formatBatchQuantity } from "../formatters";
import type { BatchPageData } from "../types";
import { CreateBatchDialog } from "./batch-dialogs";
import { BatchStatusBadge } from "./batch-status-badge";

function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof FolderKanban }) {
  return <div className="rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-foreground-muted">{label}</p><Icon aria-hidden="true" className="size-4 text-brand-strong" /></div><p className="mt-2 text-2xl font-semibold text-foreground">{value}</p></div>;
}

export function BatchesWorkspace({ project, canCreate, data }: { project: ProjectSummary; canCreate: boolean; data: BatchPageData }) {
  const [createOpen, setCreateOpen] = useState(false);
  const totalActive = data.history.reduce((sum, row) => sum + row.activeGuideCount, 0);
  const totalRollovers = data.history.reduce((sum, row) => sum + row.rolloverCount, 0);
  return <MotionPage className="mx-auto max-w-[1600px] space-y-5 pb-10">
    <MotionSection className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-brand-strong">Gestión · Operación semanal</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">Lotes semanales</h1><p className="mt-2 text-sm text-foreground-muted">Agrupa guías por semana, conserva su historial y prepara la revisión de {project.name}.</p></div>{canCreate && <button type="button" onClick={() => setCreateOpen(true)} className="primary-button gap-2"><Plus aria-hidden="true" className="size-4" /> Crear lote semanal</button>}</MotionSection>
    <MotionSection className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Lotes" value={data.history.length} icon={FolderKanban} /><Metric label="Guías activas" value={totalActive} icon={ClipboardCheck} /><Metric label="Rollovers" value={totalRollovers} icon={RotateCcw} /><Metric label="Históricos" value={data.history.filter((row) => !row.isCurrent).length} icon={History} /></MotionSection>
    <MotionSection>
      <div className="mb-3 flex items-center gap-2"><CalendarRange aria-hidden="true" className="size-4 text-brand-strong" /><h2 className="font-semibold text-foreground">Lote semanal actual</h2></div>
      {data.current ? <article className="rounded-2xl border border-brand/25 bg-surface p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-semibold text-foreground">{data.current.code}</h3><BatchStatusBadge status={data.current.status} /><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold text-foreground-muted">{data.current.source}</span></div><p className="mt-2 text-sm text-foreground-muted">{formatBatchDate(data.current.periodStart)} – {formatBatchDate(data.current.periodEnd)} · Período contable {formatBatchDate(data.current.accountingPeriod)}</p></div><Link href={`/batches/${data.current.id}`} className="primary-button gap-2">Ver detalle <ChevronRight aria-hidden="true" className="size-4" /></Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-xs text-foreground-muted">Activas</p><p className="mt-1 text-xl font-semibold">{data.current.activeGuideCount}</p></div><div><p className="text-xs text-foreground-muted">Listas</p><p className="mt-1 text-xl font-semibold text-success">{data.current.readyGuideCount}</p></div><div><p className="text-xs text-foreground-muted">Pendientes</p><p className="mt-1 text-xl font-semibold text-amber-700 dark:text-amber-300">{data.current.pendingGuideCount}</p></div><div><p className="text-xs text-foreground-muted">Recibido</p><p className="mt-1 text-sm font-semibold">{data.current.receivedByUnit.length ? data.current.receivedByUnit.map((row) => `${formatBatchQuantity(row.quantity)} ${row.unitCode}`).join(" · ") : "Sin cantidades"}</p></div></div></article> : <EmptyState icon={FolderKanban} title="No existe un lote para la semana actual" description="Crea el lote semanal cuando el equipo esté listo para agrupar guías." action={canCreate ? <button type="button" onClick={() => setCreateOpen(true)} className="primary-button">Crear lote semanal</button> : undefined} />}
    </MotionSection>
    {data.history.length > 0 && <MotionSection className="overflow-hidden rounded-xl border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold text-foreground">Historial de lotes</h2><p className="mt-1 text-xs text-foreground-muted">Semanas actuales y anteriores con sus relaciones activas.</p></div><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-muted/70 text-[10px] uppercase tracking-[0.08em] text-foreground-muted"><tr><th className="px-4 py-3">Código</th><th className="px-4 py-3">Semana</th><th className="px-4 py-3">Período contable</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Origen</th><th className="px-4 py-3">Activas</th><th className="px-4 py-3">Listas / pendientes</th><th className="px-4 py-3"><span className="sr-only">Abrir</span></th></tr></thead><tbody className="divide-y divide-border">{data.history.map((batch) => <tr key={batch.id} className="hover:bg-muted/35"><td className="px-4 py-4 font-semibold">{batch.code}</td><td className="px-4 py-4 text-foreground-muted">{formatBatchDate(batch.periodStart)} – {formatBatchDate(batch.periodEnd)}</td><td className="px-4 py-4">{formatBatchDate(batch.accountingPeriod)}</td><td className="px-4 py-4"><BatchStatusBadge status={batch.status} /></td><td className="px-4 py-4 text-foreground-muted">{batch.source}</td><td className="px-4 py-4 font-semibold">{batch.activeGuideCount}</td><td className="px-4 py-4"><span className="text-success">{batch.readyGuideCount}</span> / <span className="text-amber-700 dark:text-amber-300">{batch.pendingGuideCount}</span></td><td className="px-4 py-4 text-right"><Link href={`/batches/${batch.id}`} className="inline-grid size-9 place-items-center rounded-lg hover:bg-surface"><ChevronRight className="size-4" /></Link></td></tr>)}</tbody></table></div><div className="grid gap-3 p-4 lg:hidden">{data.history.map((batch) => <Link key={batch.id} href={`/batches/${batch.id}`} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{batch.code}</p><p className="mt-1 text-xs text-foreground-muted">{formatBatchDate(batch.periodStart)} – {formatBatchDate(batch.periodEnd)}</p></div><ChevronRight className="size-4 text-foreground-muted" /></div><div className="mt-4 flex flex-wrap items-center gap-2"><BatchStatusBadge status={batch.status} /><span className="text-xs text-foreground-muted">{batch.activeGuideCount} guías activas · {batch.source}</span></div></Link>)}</div></MotionSection>}
    {createOpen && <CreateBatchDialog project={project} onClose={() => setCreateOpen(false)} />}
  </MotionPage>;
}
