import { Files, Filter } from "lucide-react";
import { DocumentActions } from "@/components/documents/document-preview-dialog";
import { EmptyState } from "@/components/feedback/empty-state";
import { MotionPage } from "@/components/motion/motion-page";
import { getGlobalDocumentUrl } from "../actions";
import type { DocumentFilters, GlobalDocumentsData } from "../types";

function label(value: string) { return ({ GUIDE: "Guía / boleta", INCIDENT: "Evidencia de incidencia", INVOICE: "Factura", OTHER: "Otro", DISPATCH_GUIDE: "Guía / boleta", INCIDENT_EVIDENCE: "Evidencia", UPLOADED: "Disponible", PENDING: "En carga", FAILED: "Carga fallida" } as Record<string, string>)[value] ?? value; }
export function DocumentsWorkspace({ data, filters }: { data: GlobalDocumentsData; filters: DocumentFilters }) {
  return <MotionPage className="mx-auto max-w-[1500px]"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-strong">Control documental</p><h1 className="mt-2 text-2xl font-semibold text-foreground sm:text-3xl">Documentos</h1><p className="mt-2 text-sm text-foreground-muted">Consulta global sin mover ni duplicar documentos de sus expedientes originales.</p></div>
    <section className="mt-5 rounded-xl border border-border bg-surface p-4 sm:p-5"><h2 className="flex items-center gap-2 font-semibold text-foreground"><Filter className="size-4 text-brand-strong" />Filtros</h2><form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-xs text-foreground-muted">Tipo<select name="type" defaultValue={filters.type ?? ""} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground"><option value="">Todos</option><option value="DISPATCH_GUIDE">Guías / boletas</option><option value="INVOICE">Facturas</option><option value="INCIDENT_EVIDENCE">Evidencias</option></select></label>
      <label className="text-xs text-foreground-muted">Proyecto<select name="project" defaultValue={filters.projectId ?? ""} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground"><option value="">Todos</option>{data.projects.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>
      {[['order','Pedido',filters.order],['guide','Guía',filters.guide],['invoice','Factura',filters.invoice]].map(([name, title, value]) => <label key={name} className="text-xs text-foreground-muted">{title}<input name={name} defaultValue={value} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground" /></label>)}
      <label className="text-xs text-foreground-muted">Usuario<select name="user" defaultValue={filters.userId ?? ""} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground"><option value="">Todos</option>{data.users.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>
      <label className="text-xs text-foreground-muted">Desde<input type="date" name="from" defaultValue={filters.dateFrom} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground" /></label><label className="text-xs text-foreground-muted">Hasta<input type="date" name="to" defaultValue={filters.dateTo} className="mt-1.5 min-h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground" /></label>
      <div className="flex items-end gap-2"><button className="min-h-11 flex-1 rounded-lg bg-foreground px-4 text-sm font-semibold text-surface">Aplicar</button><a href="/documents" className="inline-flex min-h-11 items-center rounded-lg border border-border px-3 text-sm text-foreground-muted">Limpiar</a></div>
    </form></section>
    <section className="mt-4 overflow-hidden rounded-xl border border-border bg-surface"><header className="border-b border-border p-4 sm:p-5"><h2 className="flex items-center gap-2 font-semibold text-foreground"><Files className="size-4 text-brand-strong" />Expediente documental <span className="rounded-full bg-muted px-2 py-0.5 text-xs text-foreground-muted">{data.documents.length}</span></h2></header>
      {!data.documents.length ? <div className="p-6"><EmptyState title="Sin documentos" description="No hay documentos que coincidan con los filtros seleccionados." /></div> : <div className="divide-y divide-border">{data.documents.map((doc) => <article key={doc.id} className="grid gap-4 p-4 sm:p-5 lg:grid-cols-[minmax(0,1.5fr)_repeat(4,minmax(0,1fr))_auto] lg:items-center"><div className="min-w-0"><p className="truncate font-semibold text-foreground" title={doc.name}>{doc.name}</p><p className="mt-1 text-xs text-foreground-muted">{label(doc.context)} · {label(doc.type)}</p></div><div className="text-xs"><p className="text-foreground-muted">Contexto</p><p className="mt-1 font-medium text-foreground">{doc.orderNumber ? `Pedido ${doc.orderNumber}` : doc.invoiceNumber ? `Factura ${doc.invoiceNumber}` : "Sin Pedido"}</p></div><div className="text-xs"><p className="text-foreground-muted">Guía</p><p className="mt-1 font-medium text-foreground">{doc.guideNumber ?? "No aplica"}</p></div><div className="text-xs"><p className="text-foreground-muted">Proyecto / usuario</p><p className="mt-1 font-medium text-foreground">{doc.projectName}</p><p className="text-foreground-muted">{doc.uploadedBy}</p></div><div className="text-xs"><p className="text-foreground-muted">Fecha / estado</p><p className="mt-1 font-medium text-foreground">{new Intl.DateTimeFormat("es-GT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(doc.date))}</p><p className="text-success">{label(doc.status)}</p></div><DocumentActions projectId={doc.projectId} documentId={doc.id} fileName={doc.name} mimeType={doc.mimeType} getSignedUrl={getGlobalDocumentUrl} /></article>)}</div>}
    </section></MotionPage>;
}
